from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, model_validator


class FacilityCategory(str, Enum):
    ELECTRICAL_FIRE = "Electrical and Fire Safety"
    STRUCTURAL_SURFACE = "Structural and Surface Damage"
    PLUMBING_WATER = "Plumbing and Water Damage"
    ACCESS_SAFETY = "Access and Safety Hazards"
    FIXTURES_EQUIPMENT = "Building Fixtures and Equipment"
    SANITATION_ENVIRONMENTAL = "Sanitation and Environmental"
    ROADS_GROUNDS = "Roads, Walkways and Grounds"
    OTHER_UNCERTAIN = "Other or Uncertain"


class Urgency(str, Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


class AnalysisCertainty(str, Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"


class AnalysisStatus(str, Enum):
    ASSESSED = "Assessed"
    NO_ASSESSMENT = "No Assessment"


class ScopeDecision(str, Enum):
    FACILITY_ISSUE = "Facility Issue"
    NO_VISIBLE_ISSUE = "No Visible Maintenance Issue"
    OUT_OF_SCOPE = "Out of Scope"
    INSUFFICIENT_IMAGE = "Insufficient Image"


class ScopeValidation(BaseModel):
    model_config = ConfigDict(extra="forbid")

    decision: ScopeDecision
    should_analyze: bool
    reason: str = Field(min_length=5, max_length=300)
    detected_subjects: list[str] = Field(default_factory=list, max_length=6)

    @model_validator(mode="after")
    def validate_should_analyze(self) -> "ScopeValidation":
        expected = self.decision == ScopeDecision.FACILITY_ISSUE
        if self.should_analyze != expected:
            raise ValueError("should_analyze must match the scope decision")
        return self


class RiskFlags(BaseModel):
    model_config = ConfigDict(extra="forbid")

    immediate_danger: bool = False
    electrical_exposure: bool = False
    fire_or_smoke_indicator: bool = False
    structural_instability_indicator: bool = False
    active_flooding: bool = False
    blocked_access_or_exit: bool = False
    public_access_exposure: bool = False


class AgentAssessment(BaseModel):
    model_config = ConfigDict(extra="forbid")

    category: FacilityCategory
    summary: str = Field(min_length=5, max_length=600)
    observed_evidence: list[str] = Field(min_length=1, max_length=8)
    possible_causes: list[str] = Field(default_factory=list, max_length=5)
    safety_indicators: list[str] = Field(default_factory=list, max_length=8)
    risk_flags: RiskFlags = Field(default_factory=RiskFlags)
    recommended_urgency: Urgency
    urgency_reasons: list[str] = Field(min_length=1, max_length=6)
    estimated_min_hours: float = Field(ge=0.25, le=720)
    estimated_max_hours: float = Field(ge=0.25, le=1440)
    duration_assumptions: list[str] = Field(default_factory=list, max_length=6)
    analysis_certainty: AnalysisCertainty
    needs_review: bool
    follow_up_questions: list[str] = Field(default_factory=list, max_length=5)
    limitations: list[str] = Field(default_factory=list, max_length=6)

    @model_validator(mode="after")
    def validate_duration_range(self) -> "AgentAssessment":
        if self.estimated_max_hours < self.estimated_min_hours:
            raise ValueError("estimated_max_hours must be >= estimated_min_hours")
        return self


class ModelAssessment(BaseModel):
    """Compact internal schema generated by the vision-language model."""

    model_config = ConfigDict(extra="forbid")

    category: FacilityCategory
    summary: str = Field(min_length=5, max_length=240)
    observed_evidence: list[str] = Field(min_length=1, max_length=4)
    possible_causes: list[str] = Field(default_factory=list, max_length=2)
    risk_flags: RiskFlags = Field(default_factory=RiskFlags)
    recommended_urgency: Urgency
    urgency_reason: str = Field(min_length=3, max_length=240)
    estimated_min_hours: float = Field(ge=0.25, le=720)
    estimated_max_hours: float = Field(ge=0.25, le=1440)
    analysis_certainty: AnalysisCertainty
    needs_review: bool
    limitation: str | None = Field(default=None, max_length=240)

    @model_validator(mode="after")
    def validate_duration_range(self) -> "ModelAssessment":
        if self.estimated_max_hours < self.estimated_min_hours:
            raise ValueError("estimated_max_hours must be >= estimated_min_hours")
        return self

    def to_agent_assessment(self) -> AgentAssessment:
        safety_labels = {
            "immediate_danger": "Possible immediate danger is visible.",
            "electrical_exposure": "Possible electrical exposure is visible.",
            "fire_or_smoke_indicator": "A possible fire or smoke indicator is visible.",
            "structural_instability_indicator": (
                "A possible structural-instability indicator is visible."
            ),
            "active_flooding": "Possible active flooding is visible.",
            "blocked_access_or_exit": "Access or an exit may be blocked.",
            "public_access_exposure": "The issue may expose a public access area.",
        }
        safety_indicators = [
            label
            for field_name, label in safety_labels.items()
            if getattr(self.risk_flags, field_name)
        ]
        limitations = [self.limitation] if self.limitation else []
        follow_up_questions = (
            ["Can PPO staff inspect and confirm the affected area?"]
            if self.needs_review
            else []
        )

        return AgentAssessment(
            category=self.category,
            summary=self.summary,
            observed_evidence=self.observed_evidence,
            possible_causes=self.possible_causes,
            safety_indicators=safety_indicators,
            risk_flags=self.risk_flags,
            recommended_urgency=self.recommended_urgency,
            urgency_reasons=[self.urgency_reason],
            estimated_min_hours=self.estimated_min_hours,
            estimated_max_hours=self.estimated_max_hours,
            duration_assumptions=[
                "Preliminary estimate based on visible scope and report context."
            ],
            analysis_certainty=self.analysis_certainty,
            needs_review=self.needs_review,
            follow_up_questions=follow_up_questions,
            limitations=limitations,
        )


class ModelInspectionResponse(BaseModel):
    """Compact scope decision and optional assessment generated by the model."""

    model_config = ConfigDict(extra="forbid")

    scope_decision: ScopeDecision
    scope_reason: str = Field(min_length=5, max_length=300)
    detected_subjects: list[str] = Field(default_factory=list, max_length=6)
    assessment: ModelAssessment | None = None

    @model_validator(mode="after")
    def validate_scope_and_assessment(self) -> "ModelInspectionResponse":
        should_have_assessment = self.scope_decision == ScopeDecision.FACILITY_ISSUE
        if should_have_assessment and self.assessment is None:
            raise ValueError("assessment is required for a visible facility issue")
        if not should_have_assessment and self.assessment is not None:
            raise ValueError("assessment must be null when no assessment is appropriate")
        return self

    def to_provider_result(self) -> "ProviderAnalysis":
        should_analyze = self.scope_decision == ScopeDecision.FACILITY_ISSUE
        return ProviderAnalysis(
            scope_validation=ScopeValidation(
                decision=self.scope_decision,
                should_analyze=should_analyze,
                reason=self.scope_reason,
                detected_subjects=self.detected_subjects,
            ),
            assessment=(
                self.assessment.to_agent_assessment()
                if self.assessment is not None
                else None
            ),
        )


class ProviderAnalysis(BaseModel):
    model_config = ConfigDict(extra="forbid")

    scope_validation: ScopeValidation
    assessment: AgentAssessment | None = None


class PriorityBreakdown(BaseModel):
    urgency_points: int
    recurrence_points: int
    verification_points: int
    public_exposure_points: int
    total: int


class InspectionResult(BaseModel):
    analysis_status: AnalysisStatus
    scope_validation: ScopeValidation
    assessment: AgentAssessment | None
    priority: PriorityBreakdown | None
    provider: str
    model_id: str
    prompt_version: str
    original_width: int
    original_height: int
    processed_width: int
    processed_height: int
    processing_time_ms: int

    @model_validator(mode="after")
    def validate_result_state(self) -> "InspectionResult":
        assessed = self.analysis_status == AnalysisStatus.ASSESSED
        if assessed != self.scope_validation.should_analyze:
            raise ValueError("analysis_status must match scope_validation")
        if assessed and (self.assessment is None or self.priority is None):
            raise ValueError("assessed results require assessment and priority")
        if not assessed and (self.assessment is not None or self.priority is not None):
            raise ValueError("no-assessment results must have null assessment and priority")
        return self
