from __future__ import annotations

from dataclasses import dataclass

from .schemas import (
    AgentAssessment,
    PriorityBreakdown,
    Urgency,
)


URGENCY_POINTS = {
    Urgency.LOW: 25,
    Urgency.MEDIUM: 50,
    Urgency.HIGH: 75,
    Urgency.CRITICAL: 100,
}


@dataclass(frozen=True)
class PriorityContext:
    """
    Deterministic database-derived priority context.

    These values are NOT generated by the LLM.
    """

    recurrence_count: int = 0
    verification_count: int = 0
    age_days: float = 0.0

    recurrence_threshold: int = 2
    verification_threshold: int = 2


def calculate_priority(
    assessment: AgentAssessment,
    context: PriorityContext | None = None,
) -> PriorityBreakdown:
    context = (
        context
        or
        PriorityContext()
    )

    urgency_points = (
        URGENCY_POINTS[
            assessment.recommended_urgency
        ]
    )

    recurrence_points = (
        15
        if (
            context.recurrence_count
            >=
            context.recurrence_threshold
        )
        else 0
    )

    verification_points = (
        10
        if (
            context.verification_count
            >=
            context.verification_threshold
        )
        else 0
    )

    if context.age_days > 7:
        age_points = 20

    elif context.age_days > 3:
        age_points = 10

    else:
        age_points = 0

    public_exposure_points = (
        10
        if (
            assessment
            .risk_flags
            .public_access_exposure
        )
        else 0
    )

    total = (
        urgency_points
        +
        recurrence_points
        +
        verification_points
        +
        age_points
        +
        public_exposure_points
    )

    return PriorityBreakdown(
        urgency_points=
            urgency_points,

        recurrence_points=
            recurrence_points,

        verification_points=
            verification_points,

        age_points=
            age_points,

        public_exposure_points=
            public_exposure_points,

        total=
            total,
    )


